version: '3'

services:
  # for local mongodb
  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   env_file: ./.env
  #   environment:
  #     - mongoURI=mongodb+srv://nat:WZ8iM44EUFeumAip@cluster0.ndidq.mongodb.net/testProject?retryWrites=true&w=majority
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - db:/data/db
  app:
    #  for local mongodb
    # depends_on:
    #   - mongodb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      PORT: 5000
      mongoURI: mongodb+srv://nat:WZ8iM44EUFeumAip@cluster0.ndidq.mongodb.net/testProject?retryWrites=true&w=majority
    stdin_open: true
    tty: true

volumes:
  db:
